### ISSUE TITLE
Example not working on Windows 😁

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [GoogleCloudPlatform/functions-framework-dart#151]
This is what I did, also tried running `build_runner` command but no luck.

I use Flutter so does that make some problem for the environment?

```bash
PS C:\Users\yazee\Desktop\hello> dart run .\bin\server.dart
Unhandled exception:
SignalException: Failed to listen for SIGTERM, osError: OS Error: The request is not supported.
, errno = 50
```

Dart Version
```bash
PS C:\Users\yazee> dart --version
Dart SDK version: 2.12.0-141.0.dev (dev) (Thu Dec 10 06:04:48 2020 -0800) on "windows_x64"
```

**Comment by subfuzion** [comment]
Hmm, Windows doesn't support `SIGTERM` ... therefore, it looks like the mere act of trying to register a signal handler fails. This is a devex issue for Windows since it will work on Linux in the container that gets deployed. We can fix by detecting if we're on Windows before attempting to register the handler.

**Comment by subfuzion** [comment]
@YazeedAlKhalaf Did you run `pub get` first?
@kevmoo Are there any issues you're aware of using `build_runner` on Windows with a Flutter-only install?

**Comment by YazeedAlKhalaf** [comment]
@subfuzion  Yes, I did run `pub get`. It works fine when using docker but otherwise, it crashed with the exception above.

I believe it will be fixed once your pull request is merged?

**Comment by subfuzion** [comment]
@kevmoo Need a Windows expert to weigh in on this. While the exception would seem to indicate that SIGTERM isn't supported, I found this [old Microsoft doc](https://docs.microsoft.com/en-us/previous-versions/ms811896(v=msdn.10)?redirectedfrom=MSDN#ucmgch09_topic3) that seems to indicate that SIGTERM *is* supported. 🤷🏻‍♂️

**Comment by subfuzion** [comment]
@YazeedAlKhalaf Yeah, it works with Docker since the container actually runs in a Linux VM. As to my PR, it's just a proposed fix -- but I'm not entirely certain about it and want someone with Windows expertise to review. According to [this doc](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/signal?view=msvc-160), Windows includes `SIGTERM` for ANSI compatibility.

**Comment by YazeedAlKhalaf** [comment]
Really weird, anyway. I can confirm the fix works and I edited the pub cache with your edits and it now runs on my windows machine! 🚀

Thanks a lot 🚀 @subfuzion
